/*
 * dual_stack_echo_server.c
 *
 * This is adapted from code generated by ChatGPT and examples provided
 * in the C library documentation
 *
 */

// #include <arpa/inet.h>
// #include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
// #include <sys/socket.h>
// #include <sys/types.h>
#include <unistd.h>

#include "netex.h"

#define MESSAGE "hello world\n"

void handle_client(int client_fd) {
  send(client_fd, MESSAGE, strlen(MESSAGE), 0);
  close(client_fd);
}

int main(int argc, char *argv[]) {
  parse_server_opts(argc, argv);
  assign_tcp_dual_stack_server_fd();

  while (1) {
    struct sockaddr_storage client_addr;
    socklen_t addr_size = sizeof(client_addr);
    conn_inf.sockfd =
        accept(conn_inf.server_fd, (struct sockaddr *)&client_addr, &addr_size);
    if (conn_inf.sockfd == -1)
      continue;

    handle_client(conn_inf.sockfd);
  }

  close(conn_inf.server_fd);
  return 0;
}
