/*
 * dual_stack_echo_server.c
 *
 * This is adapted from code generated by ChatGPT and examples provided
 * in the C library documentation
 *
 */

#include <arpa/inet.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#include "netex.h"

#define MESSAGE "hello world\n"

void handle_client(int client_fd) {
  send(client_fd, MESSAGE, strlen(MESSAGE), 0);
  close(client_fd);
}

int main() {

  int server_fd = setup_tcp_dual_stack_server();

  printf("Server listening on port %s...\n", PORT);

  while (1) {
    struct sockaddr_storage client_addr;
    socklen_t addr_size = sizeof(client_addr);
    int client_fd =
        accept(server_fd, (struct sockaddr *)&client_addr, &addr_size);
    if (client_fd == -1)
      continue;

    handle_client(client_fd);
  }

  close(server_fd);
  return 0;
}
