name: C/C++ CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip python3-setuptools valgrind
        sudo -H python3 -m pip install meson ninja
    - name: configure
      run: meson builddir
    - name: ninja
      run: ninja -v -C builddir
    - name: test
      run: |
        cd builddir
        meson test -v --setup=valgrind
