name: Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/linux.yml'

  pull_request:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/linux.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install dependencies
      run: |
        sudo apt install -y \
          libsdl2-dev \
          meson \
          ninja-build

    - name: configure
      run: meson builddir -Db_sanitize=address,undefined
    - name: ninja
      run: ninja -v -C builddir
    - name: test
      run: |
        cd builddir
        meson test -v
