name: MacOS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/macos.yml'

  pull_request:
    branches: [ trunk ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/macos.yml'

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install \
          meson \
          sdl2

    - name: Meson setup
      run: |
        meson setup _build

    - name: Build
      run: |
        meson compile -C _build

    - name: Test
      run: |
        meson test -v -C _build
